// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: v1/asset.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetKind int32

const (
	AssetKind_Token AssetKind = 0
	AssetKind_Stake AssetKind = 1
	AssetKind_Loan  AssetKind = 2
)

// Enum value maps for AssetKind.
var (
	AssetKind_name = map[int32]string{
		0: "Token",
		1: "Stake",
		2: "Loan",
	}
	AssetKind_value = map[string]int32{
		"Token": 0,
		"Stake": 1,
		"Loan":  2,
	}
)

func (x AssetKind) Enum() *AssetKind {
	p := new(AssetKind)
	*p = x
	return p
}

func (x AssetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_asset_proto_enumTypes[0].Descriptor()
}

func (AssetKind) Type() protoreflect.EnumType {
	return &file_v1_asset_proto_enumTypes[0]
}

func (x AssetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetKind.Descriptor instead.
func (AssetKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_asset_proto_rawDescGZIP(), []int{0}
}

type LoanType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    AssetKind `protobuf:"varint,1,opt,name=type,proto3,enum=proto.v1.AssetKind" json:"type,omitempty"`
	Asset   string    `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount  string    `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Address string    `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *LoanType) Reset() {
	*x = LoanType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_asset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoanType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanType) ProtoMessage() {}

func (x *LoanType) ProtoReflect() protoreflect.Message {
	mi := &file_v1_asset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanType.ProtoReflect.Descriptor instead.
func (*LoanType) Descriptor() ([]byte, []int) {
	return file_v1_asset_proto_rawDescGZIP(), []int{0}
}

func (x *LoanType) GetType() AssetKind {
	if x != nil {
		return x.Type
	}
	return AssetKind_Token
}

func (x *LoanType) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *LoanType) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LoanType) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AssetType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    AssetKind `protobuf:"varint,1,opt,name=type,proto3,enum=proto.v1.AssetKind" json:"type,omitempty"`
	Address string    `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount  string    `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ChainId string    `protobuf:"bytes,4,opt,name=chainId,proto3" json:"chainId,omitempty"`
}

func (x *AssetType) Reset() {
	*x = AssetType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_asset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetType) ProtoMessage() {}

func (x *AssetType) ProtoReflect() protoreflect.Message {
	mi := &file_v1_asset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetType.ProtoReflect.Descriptor instead.
func (*AssetType) Descriptor() ([]byte, []int) {
	return file_v1_asset_proto_rawDescGZIP(), []int{1}
}

func (x *AssetType) GetType() AssetKind {
	if x != nil {
		return x.Type
	}
	return AssetKind_Token
}

func (x *AssetType) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AssetType) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *AssetType) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type StakeType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    AssetKind `protobuf:"varint,1,opt,name=type,proto3,enum=proto.v1.AssetKind" json:"type,omitempty"`
	Address string    `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount  string    `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *StakeType) Reset() {
	*x = StakeType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_asset_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StakeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeType) ProtoMessage() {}

func (x *StakeType) ProtoReflect() protoreflect.Message {
	mi := &file_v1_asset_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeType.ProtoReflect.Descriptor instead.
func (*StakeType) Descriptor() ([]byte, []int) {
	return file_v1_asset_proto_rawDescGZIP(), []int{2}
}

func (x *StakeType) GetType() AssetKind {
	if x != nil {
		return x.Type
	}
	return AssetKind_Token
}

func (x *StakeType) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StakeType) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_v1_asset_proto protoreflect.FileDescriptor

var file_v1_asset_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x7b, 0x0a, 0x08, 0x4c, 0x6f,
	0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x6b, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x2a, 0x2b, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12,
	0x09, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x6b, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x6e, 0x10, 0x02, 0x42,
	0x0a, 0x5a, 0x08, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_v1_asset_proto_rawDescOnce sync.Once
	file_v1_asset_proto_rawDescData = file_v1_asset_proto_rawDesc
)

func file_v1_asset_proto_rawDescGZIP() []byte {
	file_v1_asset_proto_rawDescOnce.Do(func() {
		file_v1_asset_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_asset_proto_rawDescData)
	})
	return file_v1_asset_proto_rawDescData
}

var file_v1_asset_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_asset_proto_goTypes = []interface{}{
	(AssetKind)(0),    // 0: proto.v1.AssetKind
	(*LoanType)(nil),  // 1: proto.v1.LoanType
	(*AssetType)(nil), // 2: proto.v1.AssetType
	(*StakeType)(nil), // 3: proto.v1.StakeType
}
var file_v1_asset_proto_depIdxs = []int32{
	0, // 0: proto.v1.LoanType.type:type_name -> proto.v1.AssetKind
	0, // 1: proto.v1.AssetType.type:type_name -> proto.v1.AssetKind
	0, // 2: proto.v1.StakeType.type:type_name -> proto.v1.AssetKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_asset_proto_init() }
func file_v1_asset_proto_init() {
	if File_v1_asset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_asset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoanType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_asset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_asset_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StakeType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_asset_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_asset_proto_goTypes,
		DependencyIndexes: file_v1_asset_proto_depIdxs,
		EnumInfos:         file_v1_asset_proto_enumTypes,
		MessageInfos:      file_v1_asset_proto_msgTypes,
	}.Build()
	File_v1_asset_proto = out.File
	file_v1_asset_proto_rawDesc = nil
	file_v1_asset_proto_goTypes = nil
	file_v1_asset_proto_depIdxs = nil
}
