name: Bob build
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install bob
        uses: benchkram/bob-install-action@v1
        with:
          version: 0.8.0

      - name: Bob build
        run: buf generate

      - name: Check Diff
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            typescript
            go

      - name: Exit if diff exists
        run: exit 1 ## fail this if the committed artifact does not match the generated one
        if: env.GIT_DIFF

      # - name: Post status to the Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.23.0
      #   if: failure()
      #   with:
      #     channel-id: ""
      #     slack-message: "${{env.DEPLOYMENT_ENV}} : Bob build failed in GH actions ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
