name: Lint Protobuf definitions
on:
  - pull_request
  - push

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1

      - name: Update dependencies
        run: buf mod update

      - run: buf lint
        name: Run Linter
