name: Lint Protobuf definitions
on:
  - pull_request
  - push

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1

      - name: Update dependencies
        run: buf mod update

      - name: Run Linter
        run: buf lint

      - name: Enforce module version
        uses: adelowo/enforce-gomod-version@v0.2.0
        with:
          modules: |
            github.com/ethereum/go-ethereum => v1.11.5
