name: Release

on:
  push:
    branches: [ main ]

jobs:
  build-test-and-release:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch tags

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true

    - name: Run tests
      run: go test ./... -coverprofile=coverage.txt

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Create GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Calculate next version tag
      id: nextver
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ steps.app-token.outputs.token }}
        default_bump: minor

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      with:
          tag_name: ${{ steps.nextver.outputs.new_tag }}
          release_name: Release ${{ steps.nextver.outputs.new_tag }}
